mapbox/variant

variant.hpp
This changes the way the compile time recursion works in the different
dispatcher classes. The recursion is ended one step earlier than before. This
way we don't need the code throwing an exception any more that's never called
anyway.
=> Change dispatcher to work without runtime error.

variant.hpp
This rips out the custom select type implementation in favor of the
C++11 conforming std::tuple_element. Note that std::tuple_element is
already included by the utility header, which includes the tuple header
itself. We only add the tuple header to be on the safe side here.
I made sure the tests via `make test` work; from `make bench` I can not
really see a difference, as the values are so small.
=> Rip out custom select_type in favor of tuple_element

variant.hpp
=> Bugfix: Duplicate call to destructor in set<>() if constructor throws.

variant.hpp
Those functions/classes don't need to be available from outside.
=> Move static_max and variant_helper into detail namespace.

variant.hpp
The comparison operator was using the wrong order when variants with different
types in them were compared. Both boost and the upcoming standard order the
types from left to right, but our implementation orders them right to left.
Boost has the function `which()` returning the index of a type in the typelist
as do we. (The upcoming standard calls this `index()`). But the comparison
operator was using `get_type_index()` which orders the types the other way
round.
=> Fix operator<().

README.md, test/bench_variant.cpp, test/binary_visitor_test.cpp, test/our_variant_hello_world.cpp, test/recursive_wrapper_test.cpp, test/unique_ptr_test.cpp, variant.hpp
Old versions of the code needed visitors to derive from static_visitor.
This is not needed any more and marked as deprecated. The static_visitor
class will be removed in future versions.
=> Deprecate static_visitor.

test/t/variant.cpp, variant.hpp
Refs #61 
A couple additions to detail::value_traits:
```c++
bool is_direct = direct_index != invalid_value;
bool is_valid = index != invalid_value;
typedef value_type = remove_reference<T>; // do it here so there's less clutter on use
typedef target_type = tuple_element<index, tuple<Types...>>
```
Because of the `target_type`, instantiation of `value_traits<T, U>` fails if `!is_convertible<T, U>`. I use this for enabling conversion constructor overloads.
I had to comment two tests because of that, I don't know how to test for "substitution failure must be an error". I tried a few things, but always ended up with `invalid use of incomplete type in std::tuple_element<0ul, std::tuple<>>`.
=> refine noexcept specifiers on constructors

variant.hpp
This looks like a leftover from the time when we didn't have std::result_of.
=> Remove unnecessary type alias.

.gitignore, .gitmodules, .travis.yml, Makefile, README.md, test/bench_variant.cpp, test/include/auto_cpu_timer.hpp, test/recursive_wrapper_test.cpp, test/unique_ptr_test.cpp
Fixes #105
cc @springmeyer @artemp
=> Install boost with mason; eliminate boost::timer dependency

include/mapbox/variant.hpp
The result of `which()` is an integer, but there's no constexpr way to get a certain types which value.
=> Add static constexpr which<T>() to obtain type ids

include/mapbox/variant.hpp
Currently, all calls to `get<type>()` check that the current type is the specified type and throw an exception if they aren't. When using `.is<type>()` to check before, this check isn't necessary and prevents usage of variant when exceptions are disabled.
=> Add get_unchecked<type>()

include/mapbox/variant.hpp
useful for adapting variant to play well with  `boost::spirit` (QI,Karma,X3)
=> expose `using types = std::tuple<Types...>;` 

Makefile, include/mapbox/variant_visitor.hpp, test/lambda_overload_test.cpp
See https://github.com/mapbox/variant/issues/113 for details.
This provides a `make_visitor` function taking lambdas and creating a
visitor functor out of it.
There are three points to conder here:
1/ Eventually we want to provide a convenient member function
so that we can plug in lambda overloads directly as in:
```c++
variant.match([] (Response) { return "ok"; },
[] (Error)    { return "error"; });
```
at the moment we still have to:
```c++
auto visitor = make_visitor([] (Response) { return "ok"; },
[] (Error)    { return "error"; });
apply_visitor(visitor, variant);
```
2/ At the moment we copy the lambdas. This is fine and follows the
stdlib but we could take them as forwarding reference instead.
3/ Maybe we should consider edge cases, such as member function pointers
and provide …
=> Provides Convenient Lambda Overload Visitor Interface, resolves #113.

include/mapbox/variant.hpp, include/mapbox/variant_visitor.hpp, test/lambda_overload_test.cpp
Part II based on our lambda overload set https://github.com/mapbox/variant/pull/124.
Member function `.match` for accepting an arbitrary number of lambdas
building a single functor out of the lambdas for visitation.
This mimics pattern matching as known from languages like Haskell,
and works with C++ lambdas for convenience. In fact lambdas are the
primary if not only use-case for this at the moment.
Usage:
```c++
variant<T, U> v;
v.match([](T){ cout << "I'm a T"; },
[](U){ cout << "I'm a U"; });
```
Note: you can use lambda captures (e.g. `[&](T){ ts += 1; }`) to
interact with the outside easily.
References:
- https://www.haskell.org/definition/haskell2010.pdf 3.17
- https://doc.rust-lang.org/book/enums.html
- https://doc.rust-lang.org/book/match.html
- …
=> Pattern Matching for Sum Types via `.match` Member Function

README.md
Note: already includes docs for `.match` https://github.com/mapbox/variant/pull/128.
Please have a look: https://github.com/daniel-j-h/variant/blob/docs/README.md#mapbox-variant
=> Adds Documentation for Readme, resolves #98

.travis.yml, Makefile, test/t/binary_visitor_impl.hpp
This PR adds `-Werror` to the default flags so that builds fail on travis that introduce new and unexpected warnings. It also:
- Fixes several warnings that were present
- Starts building in both Release and Debug mode per job (for more coverage)
- Adds a few more warning flags
=> Starts building with -Werror

Makefile
refs #133 
-D_FORTIFY_SOURCE has no effect under -O0
And there's nothing in this repo that _FORTIFY_SOURCE would check.
-fwrapv is a code-generation option
Variant, being a header-only library, should work with or without
this, and indeed will, because it doesn't rely on signed overflow
behavior. For the sake of testing, it makes more sense to test in
standard-compliant conditions, i.e. without -fwrapv.
-Wsign-compare is already enabled by -Wall -Wextra
-Wformat-security can be enabled by -Wformat=2
-Wno-unsequenced is unacceptable, unless there's a strong reason for it
Note that any warnings suppressed here will pop up in user code
using the library, and this one in particular should not be casually
suppressed.
The rest of CLANG_WARNING_FLAGS are redundant, as these warnings aren't …
=> remove useless and/or dubious compiler flags

.travis.yml
For the travis jobs using mason-provided clang++ this upgrades to the latest 3.9.1 (there is no value to testing with 3.9.0 since 3.9.1 is now available and we have full control to upgrade).
=> Target llvm 3.9.1 instead of 3.9.0

README.md
Great job on this library folks, I really appreciate just having this simple drop in for my uses.
=> Trivial missing comma in README example code

include/mapbox/variant.hpp, test/t/sizeof.cpp
by storing internal type_index as `unsigned int`
=> Making a sizeof(variant) match `boost` and `std` implementation 

test/include/catch.hpp, test/t/issue21.cpp, test/t/variant.cpp
This updates Catch to v1.9.0 and fixed some issues resulting from philsquared/Catch#823 by ensuring that we always pass an expression and not a block to the REQUIRE_THROWS and REQUIRE_THROWS_AS macros.
=> Update bundled Catch and fix resulting issues

.travis.yml, include/mapbox/variant_cast.hpp
```
class Base {public: virtual ~Base(){}};
class A: public Base {};
class B: public Base {};
typedef mapbox::util::variant<A, B> T;
T t = A();
auto &base = mapbox::util::variant_static_cast<Base>(t);
auto &a = mapbox::util::variant_dynamic_cast<A>(t);
auto &b = mapbox::util::variant_dynamic_cast<B>(t); //throws std:bad_cast
auto *aPtr = mapbox::util::variant_dynamic_cast<A*>(t);
auto *bPtr = mapbox::util::variant_dynamic_cast<B*>(t); //bPtr == nullptr
```
=> Add variant_static_cast, variant_dynamic_cast

include/mapbox/variant.hpp
=> recursive_wrapper fail to compile when used with 2 classes which are base and derived

Jamroot
Hi,
I made some improvements to support the Boost Build usage. I took a look at `Makefile` to try reflecting the following:
1. Usage of `CXX_STD` environment variable;
1. Usage of `SINGLE_THREADED` macro at single threading mode;
1. Release, single threading, optimization and `CXX_STD=-std=c++11` as default build;
1. Adding `lambda_overload_test` and `hashable_test`;
1. Removing boost bynary dependencies: `boost_system`, `boost_timer` and `boost_chrono`;
1. Usage of `out` directory to put the built targets.
The `BOOST_DIR` can now be passed through command line:
```
b2 -sBOOST_DIR=$(BOOST)
```
or
```
BOOST_DIR=$(BOOST) b2
```
*Note: The same is valid to `CXX_STD`.*
Common flags and options are in a project section and a rule `exe-test` was created to reduce de boilerplate code.
=> Improve Boost Build support

include/mapbox/variant_visitor.hpp, test/lambda_overload_test.cpp
Hi,
This pull request adds move semantics support to avoid unnecessary internal copies
of closures passed to `make_visitor` and it permits the usage of **init
capture**(feature of C++14) to use movable-only types. It also adds a
test case for lambda with init capture and movable(but not copyable)
object.
```c++
struct movable_and_copyable
{
movable_and_copyable() = default;
movable_and_copyable(movable_and_copyable&&)
{ std::cout << "move ctor" << std::endl; }
movable_and_copyable(const movable_and_copyable&) 
{ std::cout << "copy ctor" << std::endl; }
};
struct movable_only
{
movable_only() = default;
movable_only(movable_only&&) = default;
};
int main()
{
mapbox::util::variant<int, double> variant;
movable_and_copyable obj;
variant.match([obj](auto&&){});
// This legal C++14 code …
```
=> Add move semantics to make_visitor and visitor

include/mapbox/variant.hpp
We're getting annoying C4996 msvc compiler warning stating that deprecated constraint is found by compiler("was declared deprecated"). In combination with compiler flag to treat any warning as error it fails CI builds. Can we just remove deprecated `static_visitor`? Thanks
=> Removes deprecated static_visitor to avoid msvc C4996 compiler warning

Makefile, include/mapbox/variant.hpp, test/t/nothrow_move.cpp
This should allow variants to be nothrow move-assignable where appropriate.
I also took a crack at fixing the noexcept spec on the conversion assignment operator, which could previously lie. I definitely don't understand the meta-programming used here, so comments are welcome.
=> Fix the noexcept specifications for move assignment and conversion.

include/mapbox/variant.hpp
This PR adds `data` initializers wrapped in `#ifdef __clang_analyzer__` to mute static analysis warnings from Xcode (10.2).
This will significantly reduce the number of analysis warnings in `mapbox-gl-native` for iOS/macOS (see https://github.com/mapbox/mapbox-gl-native/issues/7668#issuecomment-482767630).
/cc @tmpsantos @kkaefer
=> Add explicit initialization of data to mute clang static analyzer warnings

include/mapbox/variant.hpp, test/t/optional.cpp
Addresses https://github.com/mapbox/variant/issues/164
=> Self assignment

.travis.yml, include/mapbox/variant.hpp, test/compilation_failure/get_type.cpp, test/compilation_failure/mutating_visitor_on_const.cpp, test/lambda_overload_test.cpp, test/t/optional.cpp
Fixes #142 
A note about the admittedly awkward syntax `std::move(var).match(...)`
This branch includes a change to `apply_visitor` which I forgot to put in a separate commit. Here's the deal:
```c++
mapbox::util::variant<int> v{42};
auto f = mapbox::util::make_visitor(
[](int&) { std::cout << "lvalue\n"; },
[](int&&) { std::cout << "rvalue\n"; });
mapbox::util::apply_visitor(f, v); // should print "lvalue"
mapbox::util::apply_visitor(f, std::move(v)); // should print "rvalue"
v.match(f); // what should this print?
```
Now, if you wanted this to work:
```c++
v.match([](int&&) { ... });
```
... you'd need to either
a) delegate to `visit(std::move(*this), fn)`, which might have surprising behaviour (using the visitor from the above example, `v.match(f)` would print "rvalue"); or
b) …
=> pass rvalue reference to visitor when visiting an rvalue variant
